"""cnange logs unit template key

Revision ID: ae1df5d1bc40
Revises: 13435a8c1819
Create Date: 2025-11-07 20:57:38.941187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1df5d1bc40'
down_revision: Union[str, Sequence[str], None] = '13435a8c1819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notificationlogs_template_key_key'), 'notificationlogs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('notificationlogs_template_key_key'), 'notificationlogs', ['template_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
